# Generated by Django 6.0.5 on 2026-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator')], default='moderator', max_length=20),
        ),
    ]
