# Generated by Django 6.0.4 on 2026-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_temporary_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('student', 'Student'), ('employee', 'Employee')], default='student', max_length=20),
        ),
    ]
