# Generated by Django 6.0.5 on 2026-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_has_temporary_password_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_current_admin',
            field=models.BooleanField(default=True),
        ),
    ]
