# Generated by Django 6.0.5 on 2026-09-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_itemdetails_verification_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Accessories', 'Accessories'), ('ID', 'ID'), ('Academic Materials', 'Academic Materials'), ('Bags & Wallets', 'Bags & Wallets'), ('Clothing', 'Clothing'), ('Electronic', 'Electronic'), ('Keys', 'Keys')], default='All', max_length=30),
        ),
    ]
