# Generated by Django 6.0.5 on 2026-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_alter_itemdetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='verification_options_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='verification_options_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='verification_options_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='verification_options_4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
