# Generated by Django 6.0.5 on 2026-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_itemdetails_verification_options_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Claimed', 'Claimed'), ('Returned', 'Returned'), ('Archived', 'Archived'), ('Declined', 'Declined')], default='Pending', max_length=30),
        ),
    ]
