# Generated by Django 6.0.5 on 2026-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_alter_itemdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='declined_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
