# Generated by Django 6.0.5 on 2026-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_itemdetails_declined_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='claimed_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
