# Generated by Django 6.0.5 on 2026-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_claim_meeting_time_alter_claim_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimant_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='proof_description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='AvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
