# Generated by Django 6.0.4 on 2026-08-31 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_alter_claim_claimant_name_alter_claim_meeting_time_and_more'),
        ('items', '0028_itemdetails_verification_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimant_email',
            field=models.EmailField(default='unknown@slc-sflu.edu.ph', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.itemdetails'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='proof_description',
            field=models.TextField(max_length=500),
        ),
    ]
