# Generated by Django 6.0.5 on 2026-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_claim_status_alter_claim_claimant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='answer_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='answer_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='answer_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='answer_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='other_description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='claim',
            name='question_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='question_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='question_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='question_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
