# Generated by Django 6.0.5 on 2026-09-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_claim_answer_1_claim_answer_2_claim_answer_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='staff_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
